%YAML 1.1 #<-Passa alla versione 1.1 di YAML
---
version: '3.7'

x-common-variables: # <- Crea delle variabili d'ambiente per mongo
  &mongo-variables
    MONGO_INITDB_DATABASE: animal_db
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: pass
    MONGO_HOST: mongodb+srv://cluster0.olw9u.mongodb.net
    MONGO_PORT: 27017


x-redis-common-variables: #<- Crea delle variabili d'ambiente per redis
   &redis-variables 
    REDIS_HOST: redis
    REDIS_PORT: 6379 

services: 
  api-server:
    image: ghcr.io/malizia-g/server-ci:0.0
    environment:
      <<: *mongo-variables
      <<: *redis-variables
    ports:
      - 5000:5000


  #TODO: EXPLAIN HERE
  nginx-proxy:
    restart: always
    image: ghcr.io/malizia-g/nginx-ci:0.0
    ports: 
      - 8080:8080

   
   #TODO: EXPLAIN HERE   
  client:
      image: ghcr.io/malizia-g/client-ci:0.0
      ports:
        - 4200:4200
  
   