name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [deploy]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Github Packages - ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}  

      - name: Build the DockerImage (explicit)
      - run: docker build -f ./client/Dockerfile.prod -t ghcr.io/fmalizia/client:latest ./client
      - run: docker run ghcr.io/fmalizia/client:latest
      - run: docker push ghcr.io/fmalizia/client:latest
     

      # setup Docker build action
      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v2

     
      
      # - name: Build image and push to Docker Hub and GitHub Container Registry
      #   uses: docker/build-push-action@v3
      #   with:
      #     # relative path to the place where source code with Dockerfile is located
      #     context: ./client
      #     file: Dockerfile.prod
         
      #     # build on feature branches, push only on main branch
      #     push: ${{ github.ref == 'refs/heads/main' }}

      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}